Fix wsign conversion
oatpp/oatpp pull request #836
Opened 2023-08-24 06:29 UTC by fhuberts

On top of #835 

See #784

2023-08-24 07:12 UTC, fhuberts commented
Errors in the windows build.
I did not touch that file.

```
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(35,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(36,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(49,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(43,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(45,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(47,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(57,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(58,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(60,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(59,10): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
```

Will submit a separate PR to hide those GCC pragmas behind '#ifdef __GNUC__'

2023-08-24 11:38 UTC, fhuberts commented
rebased on #835, which was rebased on #837

2023-08-24 11:39 UTC, fhuberts commented
> Errors in the windows build. I did not touch that file.
> 
> ```
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(35,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(36,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(49,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(43,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(45,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(47,16): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(57,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(58,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(60,9): warning C4068: unknown pragma 'GCC' [D:\a\1\s\build\src\oatpp.vcxproj]
> D:\a\1\s\src\oatpp\web\server\handler\ErrorHandler.cpp(59,10): warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared deprecated [D:\a\1\s\build\src\oatpp.vcxproj]
> ```
> 
> Will submit a separate PR to hide those GCC pragmas behind '#ifdef **GNUC**'

See #837

2023-08-24 12:09 UTC, fhuberts commented
I don't get it: it trips on the GCC pragmas, then I hide them and it trips on deprecated.

2023-08-27 08:49 UTC, fhuberts commented
I've pulled out the commit "Wrap GCC pragma in '#ifdef __GNUC__'"

2023-08-31 00:00 UTC, lganzzzo requested changes
Windows build is failing with the following error:

```
D:\a\1\s\src\oatpp\core\data\mapping\type\Primitive.cpp(48,62): error C2061: syntax error: identifier 'ssize_t' [D:\a\1\s\build\src\oatpp.vcxproj]
D:\a\1\s\src\oatpp\core\data\mapping\type\Primitive.cpp(58,41): error C2061: syntax error: identifier 'ssize_t' [D:\a\1\s\build\src\oatpp.vcxproj]
```

it doesn't like `ssize_t`

2023-08-31 19:21 UTC, fhuberts commented on src/oatpp/core/data/mapping/type/Primitive.cpp
> +    file.read(const_cast<char*>(result->data()), static_cast<ssize_t>(result->size()));
will take a look

2023-08-31 19:22 UTC, fhuberts commented on src/oatpp/core/data/mapping/type/Primitive.cpp
> +    fs.write(m_ptr->data(), static_cast<ssize_t>(m_ptr->size()));
will take a look

2023-08-31 19:31 UTC, closed without merging

2023-08-31 19:32 UTC, fhuberts commented
sorry, removed the wrong branch from my fork. re-instated it, and will open new PR. sorry.

2023-08-31 19:34 UTC, fhuberts commented
see #842